---
- name: Copying sql file from local to remote
  hosts: win
  fast_gathering: false
  tasks:
    - name: Converting jinja file to sql 
      template:
        src: sql_file.j2
        dest: "/tmp/{{sql_file}}.sql"

    - name: Copying the sql file to windows sharefolder
      win_copy:
        src: "/tmp/{{sql_file}}.sql"
        dest: //560/delphix_scripts/level3/
        remote_src: no
        
    - name: Copying the sql file to windows sharefolder
      win_copy:
        src: /tmp/sql_file.sql
        dest: "\\560\delphix_scripts\level3\"
        remote_src: no
