---
- name: Converting jinja file to sql 
  template:
    src: sql_file.j2
    dest: "/tmp/{{sql_file_var_name}}.sql"

- name: create directory in local machine
  file:
    path: "{{ item }}"
    mode: 0777
    state: directory
  with_items:
    - '/tmp/Sql_GIT'
  delegate_to: localhost

- name: git configuring and pulling the latest update
  command: "{{item}} chdir=/tmp/Sql_GIT"
  with_items:
   - pwd
   - git init
   - git config --global user.email "nandhinisujaxx@gmail.com"
   - git config --global user.name "Nandhini0Perumal"
   - git pull https://{{ githubuser | urlencode }}:{{ githubpassword | urlencode }}@github.com/Nandhini0Perumal/DB_Connection.git
  delegate_to: localhost
     
- name: copying the file to local git repo
  copy:
    src: /tmp/{{sql_file_var_name}}.sql
    dest: /tmp/Sql_GIT/{{sql_file_var_name}}.sql
  delegate_to: localhost

- name: git updating and pushing
  command: "{{item}} chdir=/tmp/Sql_GIT"
  with_items:
   - git add --all
   - git commit -m "test sql file added"
   - git push https://{{ githubuser | urlencode }}:{{ githubpassword | urlencode }}@github.com/Nandhini0Perumal/DB_Connection.git master
  delegate_to: localhost


- name: delete local copy
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - '/tmp/Sql_GIT'
  delegate_to: localhost

        
- name: Modifying the filename in the executable script
  become: yes
  win_lineinfile:
    path: "\\560\delphix_scripts\level3\executable_filename.ps1"
    regexp: '.*\.sql$'
    line: "{{sql_file_var_name}}.sql"
    state: present
  register: modified_result
  
- debug: var=modified_result
